### ISSUE TITLE
XML patches don't have an affect on the mod

### ISSUE THREAD

**Issue by Two-Tone** [emipa606/SimplyMoreBridges#2]
I've created a personal mod that makes most floors a little faster and was trying to add support for your bridges since I use them quite a bit, but my patch doesn't change the walk speed percent and the game doesn't throw any error.

The patch is just

```xml
    <Operation Class="PatchOperationSequence">

        <operations>
            <li Class="PatchOperationAdd">
                <xpath>/Defs/TerrainDef[@ParentName = "MoreBridgeBase"]</xpath>
                <value>
                    <pathCost>-2</pathCost>
                </value>
            </li>        
        </operations>
        
    </Operation>
```

Yet no change.  Any idea as to why?

**Comment by emipa606** [comment]
Yes, that is because this mod generates bridges of all stony and metallic materials. This happens after any patches so they wont have any effect. 
I had to generate bridges instead of usig xml since the original mod used static definitions instead of using the ”stuff” option when making bridges.

**Comment by Two-Tone** [comment]
So does it reread the xml files when it generates the new bridges instead of just grabbing it from memory? Because I don't see why patches wouldn't affect it if it generates after the patches are applied unless it just doesn't use the data in memory.

**Comment by emipa606** [comment]
It doesnt use the base-classes at all, they are only left there for compatibility reasons.

**Comment by Two-Tone** [comment]
Well damn
